name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'chan'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: |
        cd BookSearchApp
        echo sdk.dir=~/Android/Sdk >> local.properties
        echo bookApiKey=\"${{ secrets.BOOK_API_KEY }}\" >> local.prperties
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd BookSearchApp
        ./gradlew build
